### ISSUE TITLE
Incorrect edge cut renders

### ISSUE THREAD

**Issue by harshitgoel96** [tracespace/tracespace#311]
Hi,

I first want to thank you for providing such a nice tool to verify Gerber files.

I have notices an issue in the render, where the pcb edges are incorrect. I can see the outline absolutely fine in JLCPCB's gerber viewer. But the top edge is not properly showing for my pcb.

Image from live viewer
![image](https://user-images.githubusercontent.com/4772083/67028755-880cbc80-f129-11e9-8d57-20d8da795777.png)

Image for JLCPCB viewer
![image](https://user-images.githubusercontent.com/4772083/67029005-00737d80-f12a-11e9-93db-12943dec3386.png)

**Comment by mcous** [comment]
Hi @harshitgoel96, thanks for the report. Have you tried adjusting the "gap fill limit" option as suggested in the [troubleshooting guide](https://github.com/tracespace/tracespace/blob/master/apps/view/HELP.md#no-image-or-incorrect-board-shape)?

I might be able to give you more information if you were able to send me the outline file, but from looking at your screenshots, it looks like you've got some arc segments in the outline. Typically when I see incorrect board outlines involving arc segments, it's because the endpoints of the arcs don't properly meet with the endpoints of their neighboring segments, resulting in gaps in the outline that confuse the SVG fill

**Comment by mcous** [comment]
Closing due to lack of response and my assumption that this is a gap-in-the-outline issue and not an unknown bug in the plotter. Will definitely re-open if I hear back and it turns out my assumption is wrong

**Comment by harshitgoel96** [comment]
Hi. I did use arch segment. Haven't got around to fix it, as in middle of system upgrade. Will update once I fix things up.
