### ISSUE TITLE
Excellon data from PADS, all holes rendered the same size

### ISSUE THREAD

**Issue by theorganeer** [tracespace/tracespace#378]
NC Drill data generated by PADS are rendered all the same same (large) size. They appear to be as large as the largest plated hole in the design. In the attached file, there should be 10 different hole sizes.
[PADS_hole_size_off.zip](https://github.com/tracespace/tracespace/files/8328625/PADS_hole_size_off.zip)

**Comment by mcous** [comment]
Bit of a hunch, but I bet parser is missing the tool change commands because of the feed rate callouts:

```
...
T1C.015F095S3
...
```

Looking at the render, all the holes are using the last defined tool (`T10C.14`), which is the last tool definition / change command in the file without a feed-rate callout.

The regular expressions governing tool definition / change commands in drill files are located here, if you wanted to take a crack at a fix: https://github.com/tracespace/tracespace/blob/8ecba37cf1788a7d80b856b892e683af125e0cc3/packages/gerber-parser/lib/_parse-drill.js#L19-L20. Otherwise I'll try to get to this over the weekend
