### ISSUE TITLE
Provide easier way to get shareable to URL from tracespace viewer's uploaded gerber

### ISSUE THREAD

**Issue by jharwinbarrozo** [tracespace/tracespace#383]
This is a feature request. 

Basically, i need a way to share URL to my clients or anyone i want to show my work. It's weird that i need to send/share the zipped gerber for them to see. 

Thank you

**Comment by mcous** [comment]
The tracespace view app already supports a `?boardUrl` query parameter:

<https://tracespace.io/view/?boardUrl=https%3A%2F%2Ftracespace.io%2Fview%2Farduino-uno.zip>

If you pass `?boardUrl` a [URI encoded](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) pointer to a publicly hosted* ZIP file, the viewer will automatically open your file.

To do this yourself:

1. Upload your zipped board files somewhere public **that allows CORS**
2. Open the zip in tracespace view **by URL** (like the Arduino example)
3. Once the board is rendered, open the board settings and click the copy URL button

*The **publicly hosted** note is important, though. Wherever this ZIP file is hosted must allow [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) (`access-control-allow-origin *`).

Things that support CORS:
- An AWS S3 bucket configured with the proper headers
- GitHub Pages hosted content

Things that don't support CORS:
- Dropbox
- Google Drive

At this time, I do not intend to add any back-end features (like file storage or a CORS proxy) to tracespace for security and cost reasons. The viewer is likely to remain a client-side only project. Since one is already able to upload a ZIP file somewhere public and tell the viewer to directly open a given public ZIP file, I'm going to close this issue.
