### ISSUE TITLE
About Allegro CAD  drill's places

### ISSUE THREAD

**Issue by shawon1220** [tracespace/tracespace#414]
Hi, About Allegro CAD drill's places，Is it possible to be [2,5] when the unit is inches, and [3,5] when the unit is metric?
eg:
[A1000evb_daughter_cards_v1-1-4.zip](https://github.com/tracespace/tracespace/files/10660330/A1000evb_daughter_cards_v1-1-4.zip)

![image](https://user-images.githubusercontent.com/10345404/216900076-7392ca7a-274e-41c5-9840-7112b64097bc.png)
![image](https://user-images.githubusercontent.com/10345404/216900100-c13c4e6d-487c-453a-beae-2a79ad985038.png)

**Comment by shawon1220** [comment]
BBQ,This case has nc_param.txt and the places is [5,6],
[nc_param.txt](https://github.com/tracespace/tracespace/files/10660493/nc_param.txt)
[9914ce01e-1-8.zip](https://github.com/tracespace/tracespace/files/10660506/9914ce01e-1-8.zip)

**Comment by mcous** [comment]
Allegro's drill file output is quite bad, and units / coordinate format default decisions for v5 are still being made. I appreciate the feedback!

Fabs like OSHPark recommend that you select "Enhanced Excellon format". I'm not very familiar with Allegro, so I don't know what the difference is, but it may help.

Tracespace does not support `nc_param.txt` at the moment. That issue is being tracked in #392
